# Generated by Django 5.2.8 on 2025-12-06 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='Detailstable',
        ),
    ]
