# Generated by Django 5.2.8 on 2025-12-08 04:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_rename_person_detailstable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Busbooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seats', models.CharField(max_length=200)),
                ('booked_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Busdetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_name', models.CharField(max_length=100)),
                ('bus_number', models.CharField(max_length=100)),
                ('total_seats', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Busroutes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_source', models.CharField(max_length=20)),
                ('bus_destination', models.CharField(max_length=20)),
                ('bus_date', models.DateField()),
                ('bus_start_time', models.TimeField()),
                ('bus_arrival_time', models.TimeField()),
                ('bus_ticket_price', models.IntegerField()),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.busdetail')),
            ],
        ),
        migrations.DeleteModel(
            name='Detailstable',
        ),
        migrations.AddField(
            model_name='busbooking',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.busroutes'),
        ),
    ]
